version: '3.9'

services:

  # keycloak main server
  keycloak:
    container_name: keycloak
    build: ./keycloak-main
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kc-postgres:5432/keycloak #
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: changeme
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: dominic-marvin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT_HTTPS: false 
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  
  # keycloak persistence layer
  db:
    container_name: kc-postgres
    build: ./postgres
    restart: always
    # override the default values inside the Dockerfile here
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: changeme
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  # direct administration of the database (optional)
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
    

  # TODO: webapplication using keycloak to authenticate
